### ISSUE TITLE
Different versions

### ISSUE THREAD

**Issue by caskolkm** [messagebird/java-rest-api#1]
Dear MessageBird,

The docu says:

<dependency>
    <groupId>com.messagebird</groupId>
    <artifactId>messagebird-api</artifactId>
    <version>1.1.4</version>
</dependency>

when i do a mvn install, a jar with version 1.0 will be created.

Can you push this API to the public maven repository?

**Comment by samwierema** [comment]
Hi @caskolkm,

Thanks for reporting this issue.

We've updated the repository to streamline the versionining. The version is now set to 1.0.0. The API is now also available in Maven Central.
