### ISSUE TITLE
Set caption

### ISSUE THREAD

**Issue by alexvingg** [messagebird/java-rest-api#105]
Hello, 

In Message Bird SDK is not possible send media with caption. I`m using for whatsapp but this SDK don`t support this feature.

Can you help me ?

**Comment by olimpias** [comment]
Hi @alexvingg , I have created MR for this #106 . Hopefully when it is merged, you will able to use a caption for media files. Thanks!

**Comment by alexvingg** [comment]
Thanks @olimpias
When this feature will be disponible in maven repository ?

**Comment by olimpias** [comment]
We will ship it in the evenings.

**Comment by alexvingg** [comment]
Thanks @olimpias !

**Comment by denizkilic** [comment]
Hi @alexvingg,
The latest version (Release 3.0.12) is ready now. Thank you and we are welcoming more issues.
