### ISSUE TITLE
Feature request: support fallback messages

### ISSUE THREAD

**Issue by rmacqueen** [messagebird/java-rest-api#122]
The messagebird API supports fallback messages:

> Fallback Messages
> The Fallback parameter allows you to configure a message to be sent over a secondary channel if the original message failed or could not be sent within a defined time window.

As far as I can see there isn't a way to specify the fallback configuration in this Java api. Can that be added?

**Comment by olimpias** [comment]
Hi @rmacqueen , absolutely it can. I will work on it. 👍

**Comment by olimpias** [comment]
Hi @rmacqueen ,  I created MR here: #123 . After its review, we will try to release a new version as soon as possible. It is gonna be probably tomorrow or on Monday.

**Comment by denizkilic** [comment]
Hi @rmacqueen,
Support fallback messages for conversation was implemented in the latest release ([Release 3.0.16](https://github.com/messagebird/java-rest-api/releases/tag/v3.0.16)) (Special thanks to @olimpias) We are welcoming more issues if you have.
