### ISSUE TITLE
Error: wrong args about from and to recipient

### ISSUE THREAD

**Issue by SelvesNanNi** [messagebird/java-rest-api#141]
Hi,i found there is a problem about the demo which from https://github.com/messagebird/java-rest-api/blob/master/examples/src/main/java/ExampleConversationSendEmailMessage.java 

According to the line 24,in the line 34 and line 36,the index of the args array should be reversed.

**Comment by denizkilic** [comment]
Hi @SelvesNanNi,
Thanks for letting us know. We will test and update the example.
