### ISSUE TITLE
Feature Request: Adding Price For the Message object Items

### ISSUE THREAD

**Issue by katchengli** [messagebird/java-rest-api#143]
Hello,

We would like to leverage the price field from the message objects that is now available in the [message object items](https://developers.messagebird.com/api/sms-messaging/#the-message-object)

I think it should be added here:
https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/objects/MessageResponse.java#L256

Would it be possible to add it?

Thank you!

**Comment by denizkilic** [comment]
Hi @katchengli,

Of course, we will add a price field as soon as possible.

**Comment by denizkilic** [comment]
Hi @katchengli,

A new release [v3.0.21](https://github.com/messagebird/java-rest-api/releases/tag/v3.0.21) is ready to use. We are always welcoming more issues if you have.
