### ISSUE TITLE
com.messagebird.objects.ErrorReport not implement java.io.Serializable

### ISSUE THREAD

**Issue by Jasun0925** [messagebird/java-rest-api#149]
send bad_response info instead, cause: Serialized class com.messagebird.objects.ErrorReport must implement java.io.Serializable
 Java field: private java.util.List com.messagebird.exceptions.MessageBirdException.errors
 Java field: private java.lang.Throwable java.lang.Throwable.cause, dubbo version: 2.7.3, current host: 10.10.0.87"}
java.lang.RuntimeException: Serialized class com.messagebird.objects.ErrorReport must implement java.io.Serializable
 Java field: private java.util.List com.messagebird.exceptions.MessageBirdException.errors
 Java field: private java.lang.Throwable java.lang.Throwable.cause

**Comment by denizkilic** [comment]
Hi @Jasun0925 ,
The issue is solved in the latest release (v3.1.0). Please let us know if you have more issues.

**Comment by Jasun0925** [comment]
@denizkilic thank you
