### ISSUE TITLE
Media Template supported?

### ISSUE THREAD

**Issue by ssk910** [messagebird/java-rest-api#156]
Hello. I'm trying to send a message with [Media Template](https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/media-message-templates).

After I skimmed through your example classes and Java API,
I concluded that media template is not supported in your API.

Did I miss something with your API? or Should I implement my self to use media template?
Thank you. Have a nice day.

**Comment by denizkilic** [comment]
Hi @ssk910 ,

Thank you for creating this issue with the media template. Here is the [endpoint](https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/MessageBirdClient.java#L974) you will use but a "component" field is missing according to the developer [doc](https://developers.messagebird.com/quickstarts/whatsapp/send-media-template-message/#how-to-send-a-media-template-message).  ConversationContentHsm needs to be updated with [the component field.](https://developers.messagebird.com/api/conversations/#hsmlanguage-object)  We can update the class and create a new release as soon as possible. Feel free to ask any questions. Have a nice day too.

**Comment by ssk910** [comment]
@denizkilic  Thanks for your reply.
Could you please let me know when your API released?

**Comment by denizkilic** [comment]
Of course, I will let you know when the new release is ready.

**Comment by denizkilic** [comment]
Hi @ssk910,

The new release is ready with media template support. [v.3.0.2](https://github.com/messagebird/java-rest-api/releases/tag/v3.1.2) Please let us know if you have more issues.

**Comment by ssk910** [comment]
Hello @denizkilic
Thank you so much. It will be more easier to use API.
I'll open new issue if I find something wrong.
Have a nice day.
