### ISSUE TITLE
Couldn’t find conversation message list api

### ISSUE THREAD

**Issue by mingi-dev** [messagebird/java-rest-api#167]
Dear, Message Brid.

I'm found [List Message](https://developers.messagebird.com/api/conversations/#list-messages) API  in the api Reference.
It says, when try to retrieve the message list, can filter this list by ids and datetime.
But I couldn’t find any method which represents the feature I mentioned above in your Java SDK.
Does your SDK support this feature?
If it does not, could you please implement it?

**Comment by denizkilic** [comment]
Hi @mingi-dev,

Thank you for reporting the issue. I will inform you when this is implemented.

**Comment by denizkilic** [comment]
Hi @mingi-dev 

This issue is fixed by [the new release](https://github.com/messagebird/java-rest-api/releases/tag/v3.1.5). Please let us know if you have more issues.
