### ISSUE TITLE
There is a typo for an `AccessKey` class member

### ISSUE THREAD

**Issue by ssk910** [messagebird/java-rest-api#174]
Hello! 
I have checked your new release.
And then, I found an issue with an `AccessKey` member.
It is a [`mod`](https://github.com/messagebird/java-rest-api/blob/c1135a278a5b7f108072f9689567262723246369/api/src/main/java/com/messagebird/objects/AccessKey.java#L11) which is need to be replaced by a `mode`.

Thank you again for your new release.
I'll create a new issue when I find more.

**Comment by denizkilic** [comment]
Hi @ssk910 ,
A fix is merged, I will create a new release.

**Comment by denizkilic** [comment]
Hi @ssk910,
This issue is resolved in the new release. [v3.1.6](https://github.com/messagebird/java-rest-api/releases/tag/v3.1.6) Thank you. Please create more issues if you have any.

**Comment by ssk910** [comment]
Hi @denizkilic,
I checked that the issue has resolved by your new release.
Thank you.
