### ISSUE TITLE
MessageComponentType enum is wrong

### ISSUE THREAD

**Issue by npenate** [messagebird/java-rest-api#179]
The current possible values of `MessageComponentType` enum are:
```
  HEADER("header"),
  BODY("body"),
  FOOTER("footer"),
  BUTTONS("buttons");
```
The `BUTTONS` value is not a valid value since the API is expecting `BUTTON("button")`. You can see [this](https://developers.messagebird.com/quickstarts/whatsapp/send-message-with-buttons/#send-a-message-with-a-variable-url-button) example in documentation.
I have tried to make a call using `BUTTONS` but received the following error:
```
http status code: 400
{code=21, description='Content is not valid for type hsm: hsm components validation has failed. validation of component template has failed. Err: unknown component type buttons', parameter='null'}
```

**Comment by denizkilic** [comment]
Hi @npenate ,
Thank you for creating the issue. This issue will be fixed as soon as possible and I will let you know when the new release is ready.

**Comment by denizkilic** [comment]
Hi @npenate,
Enum is updated in the new release, https://github.com/messagebird/java-rest-api/releases/tag/v3.2.0  Please let us know if you have more issues.
