### ISSUE TITLE
totalDeliveryFailedCount wrong

### ISSUE THREAD

**Issue by davemaul** [messagebird/java-rest-api#201]
Hi! I'm using the MessageBird java api for sending sms to our clients. I was just messing with intentionally wrong phone numbers and wondered why all the messages are marked as sent instead of failure while the dashboard prooves otherwise.

![Screenshot 2022-05-19 at 17 58 17](https://user-images.githubusercontent.com/3143217/169344953-79385a13-bf13-47ec-9a56-d2678a5ddad9.png)

![Screenshot 2022-05-19 at 17 54 58](https://user-images.githubusercontent.com/3143217/169344817-41a20025-3f30-45b1-918f-97ab72e6c070.png)

What's the problem here?

**Comment by denizkilic** [comment]
Hi @davemaul,

`[sendMessage](https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/MessageBirdClient.java#L210)` endpoint doesn't return the information about if the SMS is actually delivered to the handset successfully or not. If you need to know this information which is called the delivery report, you should call `[viewMessage](https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/MessageBirdClient.java#L304)` endpoint with the message id which was generated when you called the `sendMessage` endpoint. These two parts are combined in the dashboard. Also, you can see example of failed SMS JSON responses below.

Response of sendMessage: 

`Sending message:
MessageResponse{id='ed1df8d4eb2a4e4ab632c00118d96450', href='https://rest.messagebird.com/messages/ed1df8d4eb2a4e4ab632c00118d96450', direction='mt', type=MsgType{value='sms'}, originator='+31633612867', body='deniz nasilsin neler yapiyorsun?', reference='null', validity=null, gateway=10, typeDetails={}, datacoding=DataCoding{value='plain'}, mclass=MClass{value=1}, scheduledDatetime=null, createdDatetime=Fri May 27 09:49:30 CEST 2022, recipients=Recipients{totalCount=1, totalSentCount=1, totalDeliveredCount=0, totalDeliveryFailedCount=0, items=[Items{recipient=90542490703, originator=null, status='sent', statusDatetime=Fri May 27 09:49:30 CEST 2022, recipientCountry='null', recipientCountryPrefix=null, recipientOperator='null', messageLength=null, statusReason='null', price=null, mccmnc='null', mcc='null', mnc='null', messagePartCount=1}]}}
`

Response of viewMessage: 

`getting message info message:
MessageResponse{id='ed1df8d4eb2a4e4ab632c00118d96450', href='https://rest.messagebird.com/messages/ed1df8d4eb2a4e4ab632c00118d96450', direction='mt', type=MsgType{value='sms'}, originator='+31633612867', body='deniz nasilsin neler yapiyorsun?', reference='null', validity=null, gateway=10, typeDetails={}, datacoding=DataCoding{value='plain'}, mclass=MClass{value=1}, scheduledDatetime=null, createdDatetime=Fri May 27 09:49:30 CEST 2022, recipients=Recipients{totalCount=1, totalSentCount=1, totalDeliveredCount=0, **totalDeliveryFailedCount=1**, items=[Items{recipient=90542490703, originator=null, status='delivery_failed', statusDatetime=Fri May 27 09:49:30 CEST 2022, recipientCountry='Turkey', recipientCountryPrefix=90, recipientOperator='Vodafone', messageLength=32, statusReason='received network error', price=Price{amount=0.0, currency=null}, mccmnc='28602', mcc='286', mnc='02', messagePartCount=1}]}}`

 Let me know if this helps.

**Comment by davemaul** [comment]
Hi @denizkilic!

Thanks for your elaboration, I'll try your solution when I have time. However, I'm curious why the fields for delivery and sent count etc. are included when they have no meaning. Could you tell me their purpose?

Greetings
