### ISSUE TITLE
Connection timed out (Read failed)

### ISSUE THREAD

**Issue by JloongChan** [messagebird/java-rest-api#205]
do send a ConversationSendRequest but cacth a Connection timed out exception after 10+ minutes,  if possible in 「getConnection(url, payload, method, headers) 」 add default connect timeout and read timeout, and then we will retry the request.

case:
2022-08-03 10:13:31.328  do send a request （MessageBirdClient#sensendMessage）
2022-08-03 10:30:00.990  catch  an exception, message is  "com.messagebird.exceptions.GeneralException: java.net.SocketException: Connection timed out (Read failed)"

**Comment by schampilomatis** [comment]
Hello, you can extend the class adding the connection configuration that you want. Example:


```
package com.messagebird;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.util.Map;

public class MessageBirdServiceWithTimeout extends MessageBirdServiceImpl {

  public MessageBirdServiceWithTimeout(String accessKey, String serviceUrl) {
    super(accessKey, serviceUrl);
  }

  public MessageBirdServiceWithTimeout(String accessKey) {
    super(accessKey);
  }

  @Override
  public <P> HttpURLConnection getConnection(String serviceUrl, P body,
      String requestType, Map<String, String> headers) throws IOException {
    HttpURLConnection connection =  super.getConnection(serviceUrl, body, requestType, headers);
    connection.setConnectTimeout(5000);
    return connection;
  }
}


```

**Comment by JloongChan** [comment]
> 

thanks.
