### ISSUE TITLE
Example for sending whatsapp template message with button ?

### ISSUE THREAD

**Issue by clerecudzio** [messagebird/java-rest-api#212]
I have scrolled through the example but i cannot find any example that includes message with buttons
Can i get any help on this ?

**Comment by denizkilic** [comment]
Hi @clerecudzio,

Here is an [example](https://github.com/messagebird/java-rest-api/blob/master/examples/src/main/java/ExampleConversationSendHSMTemplateWithButtons.java) of a WhatsApp template message with a button. If you need more help, we are ready to welcome your questions.
