### ISSUE TITLE
Language field in Verify API requests serialized incorrectly

### ISSUE THREAD

**Issue by ravi-signal** [messagebird/java-rest-api#213]
When I attempt to make a `verify` request like so:
```java
VerifyRequest request = new VerifyRequest(recipient);
request.setType(VerifyType.TTS);
request.setLanguage(Language.DE_DE);
request.setOriginator(originator);

client.sendVerifyToken(request);
```
I get back a `422` with

> Language must be one of: cy-gb, da-dk, de-de, el-gr, en-au, en-gb, en-in, en-us, es-es, es-mx, es-us, fr-ca, fr-fr, id-id, is-is, it-it, ja-jp, ko-kr, ms-my, nb-no, nl-nl, pl-pl, pt-br, pt-pt, ro-ro, ru-ru, sv-se, ta-in, th-th, tr-tr, vi-vn, zh-cn, zh-hk.

The serialized json request that ends up getting sent to the server is:
```
{
  "recipient": "redacted",
  "originator": "redacted",
  "type": "tts",
  "datacoding": "DataCoding{value=plain}",
  "language": "DE_DE"
}
```
It looks like [the `ObjectMapper` being used](https://github.com/messagebird/java-rest-api/blob/1581abfc664988b3e0ec1f75afdc6bb8fb09da01/api/src/main/java/com/messagebird/MessageBirdServiceImpl.java#L594) is using default enum serialization. The `Language` enum does have correctly cased `toString`.

One way to fix this might be to enable `toString` serialization for enums in the `ObjectMapper`

`mapper.enable(SerializationFeature.WRITE_ENUMS_USING_TO_STRING);`

but this may have other effects. 

Two other notes:
- the code tag for `RU_RU` is `ru_ru` but the API docs indicate it should be `ru-ru`
- I only see this problem for `tts`, for `sms` verify it seems like the server completely ignores the language tag, unsure if that's a separate (upstream) issue.

Thanks!

**Comment by denizkilic** [comment]
Hi @ravi-signal,

Thanks for letting us know about these issues. First, two points are resolved, we will check the third issue as soon as possible and I will let you know.

**Comment by denizkilic** [comment]
Hi @ravi-signal,
The first two issues that you stated are resolved in the [latest release.](https://github.com/messagebird/java-rest-api/releases/tag/v5.1.1) 
About the last issue, what you said about the language tag is valid about verify type TTS and verify type SMS. We only have an English template for the SMS verify type and it ignores the language tag. On the other hand, TTS doesn't ignore language tags to make it possible for customers to post templates in their own language. 
Please let us know if you have more issues.

**Comment by ravi-signal** [comment]
Thanks for your help! My issue is fully resolved, feel free to close.
