### ISSUE TITLE
HSM status is missing "DISABLED"

### ISSUE THREAD

**Issue by soda-universe** [messagebird/java-rest-api#218]
When the template is disabled due to continuous low score, the template status is "DISABLED", but it is not in the developer document and the latest release 5.1.1.
I hope that all the template statuses can be completed, and not only "DISABLED" may be omitted.
Thanks.

https://developers.messagebird.com/api/integrations/#templatestatus-object
https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/objects/integrations/HSMStatus.java

**Comment by DckcDan** [comment]
Hi soda-universe, thanks for the feedback. Our team will add the DISABLED and PAUSED statuses.
