### ISSUE TITLE
HSMCategory is outdated

### ISSUE THREAD

**Issue by jmisur** [messagebird/java-rest-api#233]
[HSMCategory](https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/objects/integrations/HSMCategory.java#L16) still shows outdated enums which were replaced [by new ones](https://developers.messagebird.com/api/integrations/#templatecategory-object) a month ago (!). Please fix this and release new version.

**Comment by denizkilic** [comment]
Hi @jmisur, 

This issue is resolved in the latest release [v6.0.0](https://github.com/messagebird/java-rest-api/releases/tag/v6.0.0).

**Comment by jmisur** [comment]
You removed legacy categories from the enum in https://github.com/messagebird/java-rest-api/commit/9b5503c8c62f1b4387bcb79724aa522771987d65.
Wouldn't an application crash if it wants to read legacy templates with old categories? Since there is no way of changing category of an existing template, I suggest bringing those values back as deprecated.
