### ISSUE TITLE
HSMCategory has not been updated

### ISSUE THREAD

**Issue by soda-universe** [messagebird/java-rest-api#234]
The article of "WhatsApp Conversation Based Pricing Changes 2023" mentions that the Category has changed, but the latest version of java sdk has not been updated. 
We can't commit WhatsApp Tempalte to Meta by sdk, please fix it as soon.

https://support.messagebird.com/hc/en-us/articles/12811470909713-WhatsApp-Conversation-Based-Pricing-Changes-2023
https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/objects/integrations/HSMCategory.java

**Comment by denizkilic** [comment]
Hi @soda-universe,
I am going to work on it and will let you know when the new release is ready.

**Comment by denizkilic** [comment]
@soda-universe the issue is resolved in the latest release [v6.0.0](https://github.com/messagebird/java-rest-api/releases/tag/v6.0.0).

**Comment by soda-universe** [comment]
> @soda-universe the issue is resolved in the latest release [v6.0.0](https://github.sheincorp.cn/messagebird/java-rest-api/releases/tag/v6.0.0).

thanks!
