### ISSUE TITLE
maxAttempts property missing from com.messagebird.objects.VerifyRequest class

### ISSUE THREAD

**Issue by atsirigotis** [messagebird/java-rest-api#252]
In the com.messagebird.objects.VerifyRequest class there should be a maxAttempts property (int) according to documentation (https://developers.messagebird.com/api/verify/#request-a-verify) that controls how many attempts are allowed before a verification fails and is set to 1 by default. If you could introduce the property and its setter, it would give us the ability to allow for more.

**Comment by denizkilic** [comment]
Hi @atsirigotis,
Thanks for raising the issue. The maxAttempts property is added in [release 6.1.6 ](https://github.com/messagebird/java-rest-api/releases/tag/v6.1.6).
