### ISSUE TITLE
2.0.0 version is not published

### ISSUE THREAD

**Issue by klpx** [messagebird/java-rest-api#45]
Hi!
Looks like version 2.0.0 mentioned in README isn't published (https://mvnrepository.com/artifact/com.messagebird/messagebird-api).

**Comment by epels** [comment]
Hi @klpx, thanks for pointing that out! It's indeed correct v2 has not been pushed to Maven yet. We'd like to add a few more changes: I'm planning on tagging and publishing v2 next week.

**Comment by epels** [comment]
Hi @klpx, [`v2.0.0`](https://mvnrepository.com/artifact/com.messagebird/messagebird-api/2.0.0) is now available on mvnrepository. Good luck!
