### ISSUE TITLE
Compatibility problem with openjdk 11

### ISSUE THREAD

**Issue by saeedafshari8** [messagebird/java-rest-api#46]
Hello guys,

It seems that the latest version of your library is not compatible with openjdk 11.
The client construction works fine but as soon as one of the APIs like client.viewLookup, the following following exception raises:
com.messagebird.exceptions.GeneralException: javax.net.ssl.SSLHandshakeException: Invalid ECDH ServerKeyExchange signature

**Comment by nperez-messagebird** [comment]
Hey there!

I'm sorry to hear there are some issues using our lib on openjdk11. I've done a little bit of research and the TL;DR seems to be there might be a bug with openjdk11 with regards to TLS.

So when I google the exception specifically, I see there are a couple of other projects that have also come across this issue. Jboss in particular seems to have [identified](https://issues.jboss.org/browse/WFLY-10812) that the default TLS implementation of 1.2 throws this exception, but if you manually set it to 1.1, it works.

There was also some [discussion](https://markmail.org/message/5ckezyfj5vj2v63r?q=net.java.openjdk&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+MarkmailNetjavaopenjdk+%28Follow+OpenJDK+development+e-mail+traffic%29) on the net.java.openjdk.security-dev mailing list around this exception if there are different crypto providers on each side of the conversation. Given our REST front end is not running java, I don't think this is an avenue to explore.

So I would try manually setting TLS to 1.1 and see if it still throws. Let us know if this doesn't work and maybe you can provide a minimal test case for us to test with so we can help you with a workaround or fix.

Best from Amsterdam,
Nick

**Comment by saeedafshari8** [comment]
Hello Nick,

Thanks for the investigation. If you've already changed the config I would say it is not working yet.

**Comment by saeedafshari8** [comment]
Hello Nick,

Thanks for the investigation. It is still not working.

**Comment by nperez-messagebird** [comment]
Hey Saeed,

Do you have a minimal test case for us to try? If you host a jar or a very simple project we can compile, it will help us a lot.

**Comment by saeedafshari8** [comment]
Thanks, the problem is solved. I cannot reproduce it furthermore.
