### ISSUE TITLE
Searching phone numbers available for purchase

### ISSUE THREAD

**Issue by olimpias** [messagebird/java-rest-api#75]
Add the feature that allows users to search phone numbers which are available for purchase. Use the below documentation link for API.

[Api Doc](https://developers.messagebird.com/api/numbers/)

**Comment by theparselmouth** [comment]
Can I take this up

**Comment by olimpias** [comment]
Sure!

**Comment by theparselmouth** [comment]
Where do you want me to write this file ? Also do I need to create an account or do you have a key for testing ?

**Comment by denizkilic** [comment]
@theparselmouth yes you can create an account for free. Test API key will be generated for your account automatically.  When you create an account, you should select "Rest API" and then select "Other API" for using Numbers API.

**Comment by antrix190** [comment]
@theparselmouth @denizkilic Is this already done? I would like to contribute if not done yet.

**Comment by theparselmouth** [comment]
Hey @antrix190 been held up at work. Feel free to give it a shot

**Comment by antrix190** [comment]
Sure @theparselmouth

**Comment by denizkilic** [comment]
Hi all,
This issue was implemented by @thewalrusisben & @Xethron in the latest release. (Release 3.0.7)
