### ISSUE TITLE
Webhook URL is not applied when set in the VoiceCall directly

### ISSUE THREAD

**Issue by katchengli** [messagebird/java-rest-api#87]
Setting the WebhookURL in a VoiceCall through the REST API allows us to receive callbacks through that specific Webhook. Using the Java SDK, it does not seem like the WebhookURL is registered at all. Is this feature not implemented yet?

It seems like the example doesn't contain it either (ie. Java https://github.com/messagebird/java-rest-api/blob/master/examples/src/main/java/ExampleSendVoiceCall.java vs Python https://github.com/messagebird/python-rest-api/blob/ebee1c3d16ca417f24bdbc7a9e6f0a6b03a5c16a/tests/test_call.py#L147)

**Comment by marcelcorso** [comment]
Hey Kat! 
There is a setter for the `webhookUrl` here: https://github.com/messagebird/java-rest-api/blob/b2496eb6e74c376a9858c54481bd80391137d993/api/src/main/java/com/messagebird/objects/voicecalls/VoiceCall.java#L67. 
Maybe it's just not on the example. Did you try it?

**Comment by katchengli** [comment]
Hi!
Thank you for verifying but we did set it. It appears on the VoiceCall object but maybe doesn't get translated properly in the request.

**Comment by Xethron** [comment]
Hello @katchengli,

Just had a look, seems like there is a problem with the JSON keys being used. Will push a fix.

**Comment by denizkilic** [comment]
Hi @katchengli 
This issue was fixed by the latest release (Release 3.0.7). Thanks @Xethron

**Comment by katchengli** [comment]
Great! Thank you!
